import { Main, Head } from '~/components'
import styles from '../styles/Home.module.css'

export default function Home() {
  const title = 'Next Zustand Counter'
  return (
    <div className={styles.container}>
      <Head 
        title={title}
        description='Generated by create next app'
      />
      <Main title={title}/>
    </div>
  )
}
