import { Main, Head } from '~/components'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head 
        title='Next Zustand Counter'
        description='Generated by create next app'
      />
      <Main />
    </div>
  )
}
